name: Report a bug
description: Report a problem with LingCode.
type: Bug
labels: "state:needs triage"
body:
  - type: markdown
    attributes:
      value: |
        Is this bug already reported? Upvote to get it noticed faster. [Here’s the search](https://github.com/Xavierhuang/lingcode_window_IDE/issues). Upvote means giving it a :+1: reaction.

        Feature request? Please open in [discussions](https://github.com/Xavierhuang/lingcode_window_IDE/discussions/new/choose) instead.
  - type: textarea
    attributes:
      label: Reproduction steps
      description: A step-by-step description of how to reproduce the bug from a **clean LingCode install**. The more context you provide, the easier it is to find and fix the problem fast.
      placeholder: |
        1. Start LingCode
        2. Click X
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current vs. Expected behavior
      description: |
        Current behavior (screenshots, videos, etc. are appreciated), vs. what you expected the behavior to be.
      placeholder: |
        Current behavior: <screenshot with an arrow> The icon is blue. Expected behavior: The icon should be red because this is what the setting is documented to do.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: LingCode version and system specs
      description: |
        Open the command palette in LingCode, then type “lingcode: copy system specs into clipboard”.
      placeholder: |
        LingCode: v1.2.1
        OS: Windows 11
        Memory: 16 GiB
        Architecture: aarch64
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attach LingCode log file
      description: |
        Open the command palette in LingCode, then type `lingcode: open log` to see the last 1000 lines. Or type `lingcode: reveal log in file manager` to reveal the log file itself.

        ⚠️ **Please review your log file for secrets (API keys, tokens, etc.) and partially or fully redact them before posting.**
      value: |
        <details><summary>LingCode.log</summary>

        <!-- Paste your log inside the code block. -->
        ```log

        ```

        </details>
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant LingCode settings
      description: |
        Open the command palette in LingCode, then type “lingcode: open settings file” and copy/paste any relevant (e.g., LSP-specific) settings.

        ⚠️ **Please review your settings file for secrets (API keys, tokens, etc.) and partially or fully redact them before posting.**
      value: |
        <details><summary>settings.json</summary>

        <!-- Paste your settings inside the code block. -->
        ```json

        ```

        </details>
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant Keymap
      description: |
        Open the command palette in LingCode, then type “lingcode: open keymap file” and copy/paste the file’s contents.
      value: |
        <details><summary>keymap.json</summary>

        <!-- Paste your keymap file inside the code block. -->
        ```json

        ```

        </details>
    validations:
      required: false
  - type: textarea
    attributes:
      label: (for AI issues) Model provider details
      placeholder: |
        - Provider: (LingModel, Kimi, Qwen, z.ai, Anthropic via API key, OpenAI, etc.)
        - Model Name:
        - Mode: (Agent Panel, Inline Assistant, or Terminal Assistant)
        - Other details (ACPs, MCPs, other settings, etc.):
    validations:
      required: false
  - type: dropdown
    attributes:
      label: If you are using WSL on Windows, what flavor of Linux are you using?
      multiple: false
      options:
        - Arch Linux
        - Ubuntu
        - Fedora
        - Mint
        - Pop!_OS
        - NixOS
        - Other
