# yaml-language-server: $schema=https://www.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/Xavierhuang/lingcode_window_IDE/discussions/new/choose
    about: To request a feature, open a new discussion under one of the appropriate categories.
  - name: Support
    url: https://lingcode.dev
    about: Have a question or need help? Visit lingcode.dev.
